"""update especie desc->nome

Revision ID: 837f5edfec74
Revises: a1c3153e772a
Create Date: 2025-09-08 23:18:22.087489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837f5edfec74'
down_revision = 'a1c3153e772a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=255), nullable=False))
        batch_op.drop_column('desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
