"""unique perfil desc

Revision ID: 8a82d98b699c
Revises: 837f5edfec74
Create Date: 2025-09-28 23:36:43.332246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a82d98b699c'
down_revision = '837f5edfec74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendas', schema=None) as batch_op:
        batch_op.alter_column('hora_inicio',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('hora_fim',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=True)

    with op.batch_alter_table('clinicas', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cnpj'])

    with op.batch_alter_table('perfis', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['desc'])

    with op.batch_alter_table('prontuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anamnese', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('suspeita_diagnostica', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['id_atendimento'])
        batch_op.drop_column('amnese')
        batch_op.drop_column('suspeita_diaginostica')

    with op.batch_alter_table('vacinas', schema=None) as batch_op:
        batch_op.alter_column('id_veterinario',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacinas', schema=None) as batch_op:
        batch_op.alter_column('id_veterinario',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('prontuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspeita_diaginostica', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amnese', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('suspeita_diagnostica')
        batch_op.drop_column('anamnese')

    with op.batch_alter_table('perfis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('clinicas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('agendas', schema=None) as batch_op:
        batch_op.alter_column('hora_fim',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('hora_inicio',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
