"""Refatora o modelo Usuario com correcoes e padronizacoes

Revision ID: a1c3153e772a
Revises: 361115c42921
Create Date: 2025-09-06 14:56:54.657581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c3153e772a'
down_revision = '361115c42921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racas', schema="public") as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=255), nullable=False))
        batch_op.drop_column('desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racas', schema="public") as batch_op:
        batch_op.add_column(sa.Column('desc', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
