from .agendas import Agenda
from .atendimentos import Atendimento
from .clinicas import Clinica
from .especies import Especie
from .perfis import Perfil
from .pets import Pet
from .prontuarios import Prontuario
from .racas import Raca
from .usuarios import Usuario
from .vacinas import Vacina
