export { default as NotFound } from "./notfound";
export { default as Home } from "./home";
export { default as Dashboard } from "./dashboard";
export { default as User } from "./user";
export { default as Login } from "./login";
export { default as Cadastro } from "./cadastro";
export { default as CadastroClinica } from "./cadastro-clinica";
export { default as CadastroVeterinario } from "./cadastro-veterinario";
export { default as QueroSerCliente } from "./quero-ser-cliente";
